version: '3.4'

services:
  php:
    image: php:8.1-fpm-alpine
    volumes:
      - ./code:/var/www/html
  nginx:
    image: nginx:stable-alpine
    ports:
      - '8082:80'
    volumes:
      - ./code:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
